name: release wasm

on:
  release:
    types: [created]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Install Just
        uses: extractions/setup-just@v1

      - name: Install toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          targets: wasm32-unknown-unknown

      - name: Check
        run: just check
        env:
          RUST_BACKTRACE: 1

      - name: Check for errors
        run: just optimize
        env:
          RUST_BACKTRACE: 1

      - name: Get release ID
        id: get_release
        uses: bruceadams/get-release@v1.3.2
        env:
          GITHUB_TOKEN: ${{ github.token }}
      - name: Upload optimized wasm
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./artifacts/*
          tag: ${{ github.ref }}
          overwrite: true
          file_glob: true
